cluster_identifier = "aurora-cluster-demo"
  engine                  = "aurora-mysql"
  engine_version          = "5.7.mysql_aurora.2.03.2"
  availability_zones      = ["us-east-2a", "us-east-2b", "us-east-2c"]
  database_name           = "mydb"
  master_username         = "foo"
  master_password         = "NEWPROJECT"
  #backup_retention_period = 5
  preferred_backup_window = "07:00-09:00"
  skip_final_snapshot  = true
  region = "us-east-2"